org: ansible-collections
repos:
  - cisco.nxos
  - cisco.ios
  - cisco.iosxr
  - arista.eos
  - vyos.vyos
  - junipernetworks.junos
  - cisco.asa
  - ansible.netcommon
maintainers:
  - name: Nilashish Chakraborty
    email: abc@test.local
triage_address: from@test.local
timedelta: 14
